apiVersion: apps/v1
kind: Deployment  
metadata:
  name: myapp-blue
  labels:
    project: myapp
    version: blue-1.0.0
spec:
  replicas: 2
  selector: 
    matchLabels:
      project: myapp
      version: blue-1.0.0
  template:
    metadata:
      labels:
        project: myapp
        version: blue-1.0.0
    containers:
    - name: nginx-blue
      image: naveenrajoli/myapp:1.0.0
      ports:
      - containerPort: 80