apiVersion: apps/v1
kind: Deployment  
metadata:
  name: myapp-blue
  labels:
    project: myapp
    version: blue-1.0.0
spec:
  replicas: 2
  selector: 
    matchLabels:
      project: myapp
      version: blue-1.0.0
  template:
    containers:
    - name: nginx-blue
      image: naveenrajoli/deployment:1.0.0
      port:
      - containerPort: 80