apiVersion: apps/v1
kind: Deployment  
metadata:
  name: myapp-green
  labels:
    project: myapp
    version: green-1.0.0
spec:
  replicas: 2
  selector: 
    matchLabels:
      project: myapp
      version: green-1.0.0
  template:
    metadata:
      labels:
        project: myapp
        version: green-1.0.0
    spec:
      containers:
      - name: nginx-green
        image: naveenrajoli/app2:1.0.0
        ports:
        - containerPort: 80
